import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const date = new Date();

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial ",
    template: "%s | Codevolution",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  `}>
        <header
          style={{
            backgroundColor: "grey",
            padding: "1rem",
            marginBottom: "2rem",
            outline: "none",
            top: 0,
            left: 0,
            width: "100%",
          }}
        >
          <ul className="flex justify-around items-center text-slate-100">
            <Link href="/">
              <li>Home</li>
            </Link>

            <Link href="/blog">
              <li>Blog</li>
            </Link>

            <Link href="/about">
              <li>About</li>
            </Link>

            <Link href="/">
              <li>Contact</li>
            </Link>
          </ul>
        </header>
        <div className="mx-32">{children}</div>

        <footer
          style={{
            backgroundColor: "grey",
            padding: "1rem",
            marginTop: "2rem",

            left: 0,
            bottom: 0,
            position: "fixed",
            width: "100%",
          }}
        >
          <p className="text-center text-slate-100">
            &copy; {date.getFullYear()}
          </p>
        </footer>
      </body>
    </html>
  );
}
